Repository storybookjs/react-native, pull requests merged in 2020-08, with the labels that each got.

#77 bug: fix typescript error during bootstrap
  app/react-native/src/preview/index.tsx
Labels: bug

#79 fix: dangerjs always fails
  .github/workflows/pull_request-dangerfile-js-pull.yml
Labels: bug

#80 fix: temporarily remove smoke test since it's broken
  .circleci/config.yml
Labels: maintenance

#70 chore: use native switch component
  addons/ondevice-knobs/package.json
  addons/ondevice-knobs/src/types/Boolean.js
  yarn.lock
Labels: addon: knobs, bug

#74 fix(): update react-native-modal-selector to new version
  addons/ondevice-knobs/package.json
  yarn.lock
Labels: addon: knobs, dependencies:update, has workaround

#83 feat(addon-knobs): add radios type
  addons/ondevice-knobs/src/PropField.js
  addons/ondevice-knobs/src/components/RadioSelect.js
  addons/ondevice-knobs/src/types/Radio.js
  addons/ondevice-knobs/src/types/index.js
  examples/native/ios/Podfile.lock
Labels: addon: knobs, enhancement, feature request

#87 fix: detox will run twice on every PR
  .github/workflows/detox.yml
Labels: maintenance

#85 fix: temporary fix for color picker
  .eslintignore
  .remarkignore
  addons/ondevice-knobs/package.json
  addons/ondevice-knobs/src/components/color-picker/HoloColorPicker.js
  addons/ondevice-knobs/src/components/color-picker/TriangleColorPicker.js
  addons/ondevice-knobs/src/components/color-picker/index.d.ts
  addons/ondevice-knobs/src/components/color-picker/index.js
  addons/ondevice-knobs/src/components/color-picker/resources/color-circle.png
  addons/ondevice-knobs/src/components/color-picker/resources/color-circle.xcf
  addons/ondevice-knobs/src/components/color-picker/resources/hsv_triangle_mask.png
  addons/ondevice-knobs/src/components/color-picker/utils.js
  addons/ondevice-knobs/src/types/Color.js
  yarn.lock
Labels: bug

#90 docs: update getting started guide
  README.md
Labels: documentation

#93 Add 5.3 compatibility disclaimer
  README.md
Labels: documentation

#89 Feat:update expo example app
  examples/crna-kitchen-sink/app.json
  examples/crna-kitchen-sink/assets/favicon.png
  examples/crna-kitchen-sink/assets/icon.png
  examples/crna-kitchen-sink/assets/splash.png
  examples/crna-kitchen-sink/metro.config.js
  examples/crna-kitchen-sink/package.json
  examples/crna-kitchen-sink/storybook/index.js
  yarn.lock
Labels: maintenance

#94 fix: emit type declarations when building so type info is not lost
  scripts/compile-tsc.js
Labels: maintenance

#97 fix: revert master branch to 5.3.19 version
  addons/ondevice-actions/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  app/react-native-server/package.json
  app/react-native/package.json
  examples/crna-kitchen-sink/package.json
  examples/native/ios/Podfile.lock
  examples/native/package.json
  lerna.json
  package.json
  yarn.lock
Labels: maintenance

#100 fix: server addons and update all dependencies to use storybook 5.3.20
  .github/workflows/detox.yml
  addons/ondevice-actions/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  app/react-native-server/package.json
  app/react-native/package.json
  examples/crna-kitchen-sink/package.json
  examples/native/package.json
  package.json
  yarn.lock
Labels: app: react-native-server, bug, maintenance

#99 docs: some basic info about setting up the server
  README.md
Labels: documentation, in progress

#102 chore: upgrade storybook deps to 5.3.21
  addons/ondevice-actions/package.json
  addons/ondevice-backgrounds/package.json
  addons/ondevice-knobs/package.json
  addons/ondevice-notes/package.json
  app/react-native-server/package.json
  app/react-native/package.json
  examples/crna-kitchen-sink/package.json
  examples/native/package.json
  yarn.lock
Labels: maintenance
