Repository storybookjs/react-native, pull requests merged in 2020-11, with the labels that each got.

#118 fix: size of on-device radios knob is inconsistent with other knobs
  addons/ondevice-knobs/src/components/RadioSelect.js
Labels: bug

#137 Reset groupId when a story is selected
  addons/ondevice-knobs/src/panel.js
Labels: addon: knobs, bug

#88 fix: potential fix for status bar covering stories on android+expo
  app/react-native/src/preview/components/OnDeviceUI/index.tsx
Labels: ui
