Repository storybookjs/react-native, pull requests merged in 2021-07, with the labels that each got.

#218 fix: Fixes #211 (After opening the keyboard the android UI shrinks)
  app/react-native/src/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view.tsx
  examples/native/ios/Podfile.lock
Labels: 6.0

#217 [6.0] Removed FunctionComponent type
  addons/ondevice-actions/src/components/ActionLogger/index.tsx
  addons/ondevice-backgrounds/src/Swatch.tsx
  app/react-native/src/preview/components/StoryListView/StoryListView.tsx
  examples/native/components/ControlExamples/Color/Color.tsx
  examples/native/components/ControlExamples/Select/Select.tsx
  examples/native/components/PromiseTest/Button.tsx
  examples/native/other_components/AnotherButton/AnotherButton.tsx
Labels: 6.0

#221 feat: add array control type
  addons/ondevice-controls/src/types/Array.tsx
  addons/ondevice-controls/src/types/index.ts
  examples/native/components/ControlExamples/Array/Array.stories.tsx
  examples/native/components/ControlExamples/Array/Array.tsx
Labels: 6.0

#223 feat: add date control type
  addons/ondevice-controls/package.json
  addons/ondevice-controls/src/types/Date.tsx
  addons/ondevice-controls/src/types/index.ts
  examples/native/components/ControlExamples/Date/Date.stories.tsx
  examples/native/components/ControlExamples/Date/Date.tsx
  examples/native/ios/Podfile.lock
  examples/native/package.json
  yarn.lock
Labels: 6.0

#220 feat: add text input story to example
  examples/native/components/InputExample/TextInput.stories.tsx
Labels: 6.0

#224 fix: Fixes selected story changing when editing the story file
  app/react-native/src/preview/Preview.tsx
  app/react-native/src/preview/components/OnDeviceUI/OnDeviceUI.tsx
Labels: 6.0

#226 feat: adds a prepareall script
  package.json
Labels: 6.0

#229 feat: Reintroduce the backgrounds addon
  addons/ondevice-backgrounds/README.md
  addons/ondevice-backgrounds/src/BackgroundPanel.tsx
  examples/native/.storybook/main.js
  examples/native/.storybook/preview.js
  examples/native/components/BackgroundExample/Background.stories.tsx
  examples/native/components/BackgroundExample/BackgroundCsf.stories.tsx
  examples/native/package.json
Labels: 6.0, addon: backgrounds

#228 fix: Fixes the "`storyFn` is deprecated and will be removed in Storybook 7.0." deprecation warning
  app/react-native/src/preview/components/StoryView/StoryView.tsx
Labels: 6.0

#231 feat: radio control
  addons/ondevice-controls/src/components/RadioSelect.tsx
  addons/ondevice-controls/src/types/Button.tsx
  addons/ondevice-controls/src/types/Radio.tsx
  addons/ondevice-controls/src/types/index.ts
  examples/native/components/ControlExamples/Radio/Radio.stories.tsx
  examples/native/components/ControlExamples/Radio/Radio.tsx
  package.json
Labels: 6.0

#234 fix: better example for select control
  addons/ondevice-controls/src/types/Select.tsx
  examples/native/components/ControlExamples/Select/Select.stories.tsx
Labels: 6.0

#233 feat: add ondevice actions for 6.0
  addons/ondevice-actions/package.json
  addons/ondevice-actions/src/index.tsx
  app/react-native/scripts/loader.js
  app/react-native/src/index.ts
  examples/native/.storybook/main.js
  examples/native/components/ActionExample/Actions.stories.tsx
  examples/native/components/ActionExample/Actions.tsx
  examples/native/package.json
Labels: 6.0, addon: actions
